// All editable site content lives here. Each text is {tr, en}.
export const T = (tr, en) => ({ tr, en });

// ⚠ PLACEHOLDERS: replace phone, WhatsApp, email, address, hours and domain with the real details.
export const CFG = {
  name: 'Gebze Dental Klinik',
  doctor: 'Dt. Esra Bozdemir Yazıcı',
  siteUrl: 'https://gebzedentalklinik.com',
  phone: '+90 541 360 36 80',
  phoneRaw: '+905413603680',
  whatsapp: '905413603680',
  email: 'info@gebzedentalklinik.com',
  address: T('Hacıhalil, 1227. Sk. No: 3B, 41400 Gebze/Kocaeli', 'Hacıhalil, 1227. Sk. No: 3B, 41400 Gebze/Kocaeli, Türkiye'),
  mapsUrl: 'https://maps.app.goo.gl/yyZbtAmvwYGVumuG9',
  mapQuery: 'Hacıhalil, 1227. Sk. No: 3B, 41400 Gebze/Kocaeli',
  hours: {
    tr: [['Pazartesi – Cuma', '09:30 – 20:00'], ['Cumartesi', '09:30 – 18:00'], ['Pazar', 'Kapalı']],
    en: [['Monday – Friday', '09:30 – 20:00'], ['Saturday', '09:30 – 18:00'], ['Sunday', 'Closed']],
  },
};

export const TEAM = {
  doctors: [
    { name: 'Dt. Esra Bozdemir Yazıcı', role: T('Diş Hekimi', 'Dentist'), photo: '/assets/img/dr-esra.jpg', bio: T('Tüm tedavileri tek klinikte yürütür. Tedaviyi sade bir dille anlatır ve seçenekleri hastasıyla birlikte değerlendirir.', 'Provides all treatments in one clinic. Explains treatment in plain language and weighs the options together with each patient.') },
    { name: 'Dt. Şevval Doğrusoy Kan', role: T('Diş Hekimi', 'Dentist'), photo: null, bio: null },
  ],
  assistants: [
    { name: 'Havva', role: T('Klinik Asistanı', 'Dental Assistant'), photo: null },
    { name: 'Tuana', role: T('Klinik Asistanı', 'Dental Assistant'), photo: null },
  ],
};

export const GROUPS = [
  { id: 'everyday', icon: 'tooth', name: T('Günlük Diş Bakımı', 'Everyday Care'), promise: T('Muayene, dolgu, kanal ve diş eti: dişlerinizi sağlıklı tutan temel tedaviler.', 'Check-ups, fillings, root canals and gum care: the basics that keep your teeth healthy.') },
  { id: 'cosmetic', icon: 'sparkle', name: T('Estetik ve Şeffaf Plak', 'Cosmetic & Clear Aligners'), promise: T('Görünmez plaklarla düzgün, dijital planlı bir gülüş.', 'A straight, digitally planned smile with invisible aligners.') },
  { id: 'implant', icon: 'crosshair', name: T('İmplant ve Cerrahi', 'Implants & Surgery'), promise: T('Cerrahi guide ile planlı implant, diş çekimi ve protez çözümleri.', 'Guided implant surgery, extractions and prosthetic solutions.') },
  { id: 'emergency', icon: 'alert', name: T('Acil', 'Emergency'), promise: T('Ağrı, şişlik veya kırık diş: en kısa sürede yanınızdayız.', 'Pain, swelling or a broken tooth: we are here as soon as possible.') },
];

export const TREATMENTS = [
  {
    group: 'everyday', icon: 'search', slug: T('muayene-ve-dis-tasi-temizligi', 'check-up-and-cleaning'),
    name: T('Muayene ve Diş Taşı Temizliği', 'Check-up & Scaling'),
    promise: T('Sorunlar büyümeden fark edilir; dişleriniz ve diş etleriniz temiz kalır.', 'Problems are spotted before they grow, and your teeth and gums stay clean.'),
    who: T('Herkes için. Altı ayda bir kontrol önerilir.', 'For everyone. A check-up every six months is recommended.'),
    steps: T(['Ağız muayenesi ve gerekirse röntgen', 'Ultrasonik diş taşı temizliği ve cilalama', 'Size özel bakım önerileri'], ['Oral exam and X-rays if needed', 'Ultrasonic scaling and polishing', 'Personalised home-care advice']),
    duration: T('Yaklaşık 30–45 dakika, tek seans', 'About 30–45 minutes, one visit'),
    faq: [{ q: T('Diş taşı temizliği dişlere zarar verir mi?', 'Does scaling damage the teeth?'), a: T('Doğru uygulandığında hayır. Diş eti sağlığını korur; ilk günlerde hafif hassasiyet olabilir.', 'Not when done properly. It protects gum health; mild sensitivity may last a few days.') }],
  },
  {
    group: 'everyday', icon: 'tooth', slug: T('dis-dolgusu', 'dental-fillings'),
    name: T('Estetik Diş Dolgusu', 'Tooth-coloured Fillings'),
    promise: T('Çürüğü temizler, dişinizi doğal rengiyle onarırız.', 'We remove the decay and restore the tooth in its natural colour.'),
    who: T('Çürük, kırık veya aşınmış dişleri olanlar için.', 'For decayed, chipped or worn teeth.'),
    steps: T(['Muayene ve çürüğün tespiti', 'Çürüğün temizlenmesi (gerekirse lokal anestezi)', 'Kompozit dolgu uygulaması ve cilalama'], ['Exam and diagnosis of the decay', 'Decay removal (local anaesthesia if needed)', 'Composite filling and polishing']),
    duration: T('30–60 dakika, çoğunlukla tek seans', '30–60 minutes, usually one visit'),
    faq: [{ q: T('Dolgu ne kadar dayanır?', 'How long does a filling last?'), a: T('Bakıma bağlı olarak yıllarca. Düzenli kontroller ömrünü uzatır.', 'Many years, depending on care. Regular check-ups extend its life.') }],
  },
  {
    group: 'everyday', icon: 'shield', slug: T('kanal-tedavisi', 'root-canal-treatment'),
    name: T('Kanal Tedavisi', 'Root Canal Treatment'),
    promise: T('Dişinizi çekmeden kurtarmayı hedefleriz.', 'Our aim is to save your tooth instead of extracting it.'),
    who: T('Derin çürük, şiddetli ağrı veya enfeksiyonu olan dişler için.', 'For teeth with deep decay, severe pain or infection.'),
    steps: T(['Anestezi ve enfekte dokunun temizlenmesi', 'Kanalların şekillendirilip dezenfekte edilmesi', 'Kanal dolgusu ve gerekirse kaplama'], ['Anaesthesia and removal of infected tissue', 'Shaping and disinfecting the canals', 'Canal filling and a crown if needed']),
    duration: T('1–3 seans, vakaya göre', '1–3 visits, depending on the case'),
    faq: [{ q: T('Kanal tedavisi ağrılı mıdır?', 'Is a root canal painful?'), a: T('Lokal anestezi altında yapılır, işlem sırasında ağrı beklenmez. Sonrasında birkaç gün hafif hassasiyet olabilir.', 'It is done under local anaesthesia, so you should feel no pain. Mild tenderness may follow for a few days.') }],
  },
  {
    group: 'everyday', icon: 'smile', slug: T('cocuk-dis-tedavisi', 'childrens-dentistry'),
    name: T('Çocuk Diş Tedavisi', "Children's Dentistry"),
    promise: T('Çocukların diş hekimine güvenle alışması için sabırlı bir yaklaşım.', 'A patient approach that helps children get comfortable at the dentist.'),
    who: T('Süt dişi ve erken karma dişlenme dönemindeki çocuklar.', 'Children with baby teeth or early mixed dentition.'),
    steps: T(['Tanışma ve rahat bir ağız muayenesi', 'Koruyucu uygulamalar (fissür örtücü, flor)', 'Gerekirse dolgu ve düzenli takip'], ['Getting acquainted and a relaxed exam', 'Preventive care (sealants, fluoride)', 'Fillings if needed and regular follow-up']),
    duration: T('20–40 dakika', '20–40 minutes'),
    faq: [{ q: T('İlk diş hekimi ziyareti ne zaman olmalı?', 'When should the first dental visit be?'), a: T('İlk süt dişi çıktığında, en geç bir yaşına kadar önerilir.', 'When the first baby tooth appears, and no later than the first birthday.') }],
  },
  {
    group: 'everyday', icon: 'heart', slug: T('dis-eti-tedavisi', 'gum-treatment'),
    name: T('Diş Eti Tedavisi', 'Gum Treatment'),
    promise: T('Kanayan veya çekilen diş etlerini erken dönemde kontrol altına alın.', 'Bring bleeding or receding gums under control early.'),
    who: T('Diş eti kanaması, kötü nefes veya diş sallanması olanlar.', 'Anyone with bleeding gums, bad breath or loose teeth.'),
    steps: T(['Diş eti ve kemik değerlendirmesi', 'Kök yüzeyi temizliği (küretaj)', 'Bakım programı ve kontrol seansları'], ['Gum and bone assessment', 'Deep root cleaning (scaling and root planing)', 'Maintenance plan and follow-up visits']),
    duration: T('1–3 seans', '1–3 visits'),
    faq: [{ q: T('Diş eti kanaması normal mi?', 'Is gum bleeding normal?'), a: T('Değil. Genellikle diş eti iltihabının işaretidir ve muayene gerektirir.', 'No. It usually signals gum inflammation and needs an exam.') }],
  },
  {
    group: 'cosmetic', icon: 'aligner', featured: true, slug: T('seffaf-plak-tedavisi', 'clear-aligners'),
    name: T('Şeffaf Plak Tedavisi', 'Clear Aligners'),
    promise: T('Tel olmadan, görünmez ve çıkarılabilir plaklarla düzgün dişler.', 'Straighter teeth with invisible, removable aligners and no wires.'),
    who: T('Çapraşıklık, aralık veya kapanış sorunu olan yetişkin ve gençler. Uygunluk muayene ile belirlenir.', 'Adults and teens with crowding, gaps or bite issues. Suitability is decided at the exam.'),
    steps: T(['Muayene, dijital ölçü ve fotoğraflarla hedef gülüşün planlanması', 'Tedavinin adım adım 3D simülasyonu ve onayınız', 'Plak setinin hazırlanması ve düzenli değiştirilmesi', 'Aralıklı kontroller ve sonucu koruyan retainer'], ['Exam, digital records and photos to plan the target smile', 'A step-by-step 3D simulation for your approval', 'Custom aligner sets, changed on schedule', 'Regular check-ups and a retainer to keep the result']),
    duration: T('Genellikle 6–18 ay; vakaya göre değişir', 'Typically 6–18 months; varies by case'),
    faq: [{ q: T('Plaklar günde kaç saat takılmalı?', 'How many hours a day are aligners worn?'), a: T('Genellikle günde 20–22 saat. Yemek ve diş fırçalama sırasında çıkarılır.', 'Usually 20–22 hours a day. You remove them to eat and brush.') }, { q: T('Herkes şeffaf plak kullanabilir mi?','Is everyone a candidate?'), a: T('Çoğu vaka uygundur; bazı karmaşık vakalarda farklı yöntemler gerekebilir. Muayenede net cevap veririz.', 'Most cases are suitable; some complex ones need another method. We will tell you clearly at the exam.') }],
  },
  {
    group: 'cosmetic', icon: 'smile', slug: T('ortodonti', 'orthodontics'),
    name: T('Ortodonti (Tel ve Şeffaf Plak)', 'Orthodontics (Braces & Clear Aligners)'),
    promise: T('Çapraşık dişleri ve kapanış sorunlarını tel veya şeffaf plakla düzeltiyoruz.', 'We correct crooked teeth and bite problems with braces or clear aligners.'),
    who: T('Dişlerinde çapraşıklık, aralık veya çene uyumsuzluğu olan çocuk, genç ve yetişkinler.', 'Children, teens and adults with crowding, gaps or jaw misalignment.'),
    steps: T(['Muayene, ölçü ve fotoğraflarla ortodontik değerlendirme', 'Size uygun yöntemin (tel veya şeffaf plak) birlikte seçilmesi', 'Düzenli kontrollerle dişlerin adım adım hizalanması', 'Sonucu koruyan retainer (tutucu) uygulaması'], ['Orthodontic assessment with an exam, impressions and photos', 'Choosing the right method (braces or clear aligners) together', 'Step-by-step alignment with regular check-ups', 'A retainer to keep the result']),
    duration: T('Vakaya göre değişir; genellikle aylar veya yıllar sürer', 'Varies by case; usually months to a couple of years'),
    faq: [{ q: T('Tel mi şeffaf plak mı?', 'Braces or clear aligners?'), a: T('Dişlerin durumuna, yaşınıza ve beklentinize göre birlikte karar veririz. Şeffaf plak her vakaya uygun olmayabilir.', 'We decide together based on your teeth, age and expectations. Clear aligners may not suit every case.') }],
  },
  {
    group: 'cosmetic', icon: 'sparkle', slug: T('dis-beyazlatma', 'teeth-whitening'),
    name: T('Diş Beyazlatma', 'Teeth Whitening'),
    promise: T('Dişlerinizi zarar vermeden birkaç ton açın.', 'Brighten your teeth by several shades, safely.'),
    who: T('Sağlıklı dişleri olup renk açılması isteyenler.', 'People with healthy teeth who want a brighter shade.'),
    steps: T(['Muayene ve diş taşı temizliği', 'Diş etini koruyarak beyazlatma jeli uygulaması', 'Sonuç sonrası bakım önerileri'], ['Exam and scaling', 'Whitening gel applied while protecting the gums', 'Aftercare advice']),
    duration: T('Bir veya iki seans', 'One or two visits'),
    faq: [{ q: T('Beyazlatma hassasiyet yapar mı?', 'Does whitening cause sensitivity?'), a: T('Geçici hassasiyet olabilir; uygun jel ve teknikle en aza indirilir.', 'Temporary sensitivity is possible; the right gel and technique keep it minimal.') }],
  },
  {
    group: 'cosmetic', icon: 'layers', slug: T('laminate-veneer', 'porcelain-veneers'),
    name: T('Laminate Veneer (Porselen)', 'Porcelain Veneers'),
    promise: T('Renk, şekil ve boy uyumuyla doğal görünen bir gülüş.', 'A natural-looking smile with matched colour, shape and length.'),
    who: T('Ön dişlerinin rengini veya şeklini değiştirmek isteyenler.', 'People who want to change the colour or shape of their front teeth.'),
    steps: T(['Gülüş analizi ve dijital tasarım', 'Dişlerin minimal hazırlanması ve ölçü', 'Laminelerin uygulanması'], ['Smile analysis and digital design', 'Minimal tooth preparation and impressions', 'Placing the veneers']),
    duration: T('2–3 seans', '2–3 visits'),
    faq: [{ q: T('Laminate dişe zarar verir mi?', 'Do veneers harm the tooth?'), a: T('Çok ince bir hazırlık gerekir; bu yüzden doğru vaka seçimi önemlidir. Muayenede birlikte karar veririz.', 'A very thin preparation is needed, so case selection matters. We decide together at the exam.') }],
  },
  {
    group: 'cosmetic', icon: 'camera', slug: T('dijital-gulus-tasarimi', 'digital-smile-design'),
    name: T('Dijital Gülüş Tasarımı', 'Digital Smile Design'),
    promise: T('Sonucu tedaviden önce ekranda görün.', 'See the result on screen before treatment begins.'),
    who: T('Estetik tedavi öncesi net bir plan görmek isteyenler.', 'Anyone who wants a clear plan before cosmetic treatment.'),
    steps: T(['Fotoğraf ve ölçülerin alınması', 'Dijital tasarım ve önizleme', 'Onayınız sonrası tedavinin uygulanması'], ['Photos and measurements', 'Digital design and preview', 'Treatment once you approve']),
    duration: T('Planlama tek seans; uygulama tedaviye göre', 'Planning takes one visit; treatment time varies'),
    faq: [{ q: T('Tasarım kesin sonuç garantisi midir?', 'Does the design guarantee the result?'), a: T('Önizleme hedefi gösterir; nihai sonuç diş yapısına ve uygulanan tedaviye bağlıdır.', 'The preview shows the goal; the final result depends on your teeth and the treatment.') }],
  },
  {
    group: 'implant', icon: 'implant', slug: T('dis-implanti', 'dental-implants'),
    name: T('Diş İmplantı', 'Dental Implants'),
    promise: T('Eksik dişin yerine sağlam, doğal görünen kalıcı çözüm.', 'A solid, natural-looking permanent replacement for a missing tooth.'),
    who: T('Bir veya birden fazla dişi eksik olanlar.', 'People missing one or more teeth.'),
    steps: T(['3D görüntüleme ve dijital planlama', 'Lokal anestezi ile implantın yerleştirilmesi', 'İyileşme sonrası porselen kron'], ['3D imaging and digital planning', 'Implant placement under local anaesthesia', 'Porcelain crown after healing']),
    duration: T('İyileşme dahil birkaç ay; vakaya göre', 'A few months including healing; varies by case'),
    faq: [{ q: T('İmplant herkese uygulanabilir mi?', 'Can everyone get an implant?'), a: T('Yeterli kemik ve sağlıklı diş eti gerekir; 3D görüntüleme ile değerlendirilir.', 'Enough bone and healthy gums are needed; we assess this with 3D imaging.') }],
  },
  {
    group: 'implant', icon: 'crosshair', featured: true, slug: T('cerrahi-guide-ile-implant', 'guided-implant-surgery'),
    name: T('Cerrahi Guide ile İmplant', 'Guided Implant Surgery'),
    promise: T('Dijital planlanan yere, planlanan açıyla: kılavuzlu implant cerrahisi.', 'Placed where it was planned, at the planned angle: guided implant surgery.'),
    who: T('İmplantı daha öngörülebilir ve kontrollü bir işlemle yaptırmak isteyenler. Uygunluk vakaya göre belirlenir.', 'Those who want a more predictable, controlled implant procedure. Suitability depends on the case.'),
    steps: T(['3D tomografi ve dijital ölçü birleştirilir', 'Yazılımda implantın konumu ve açısı planlanır', 'Plan, kişiye özel cerrahi guide (kılavuz) ile ağıza aktarılır', 'İmplant kılavuz eşliğinde yerleştirilir'], ['3D scan and digital impressions are combined', 'Implant position and angle are planned in software', 'A custom surgical guide transfers the plan to the mouth', 'The implant is placed through the guide']),
    duration: T('Planlama seansı + cerrahi seansı', 'One planning visit + one surgical visit'),
    faq: [{ q: T('Her implant cerrahi guide ile mi yapılır?', 'Is every implant done with a guide?'), a: T('Hayır. Kemik yapısı ve vakanın özelliğine göre guide kullanılıp kullanılmayacağına birlikte karar veririz.', 'No. We decide together whether to use a guide based on your bone and the case.') }],
  },
  {
    group: 'implant', icon: 'crosshair', slug: T('agiz-dis-ve-cene-cerrahisi', 'oral-and-maxillofacial-surgery'),
    name: T('Ağız, Diş ve Çene Cerrahisi', 'Oral & Maxillofacial Surgery'),
    promise: T('Gömülü diş çekimi, kök operasyonları ve ileri cerrahi işlemler.', 'Impacted tooth removal, root surgery and advanced surgical procedures.'),
    who: T('Gömülü dişi, kist veya diş kökü sorunu olanlar; cerrahi gerektiren vakalar.', 'People with impacted teeth, cysts or root problems, and cases that need surgery.'),
    steps: T(['Muayene ve röntgen veya 3D görüntüleme ile planlama', 'Lokal anestezi altında cerrahi işlem', 'Dikiş, bakım talimatları ve kontrol seansı'], ['Exam and planning with X-rays or 3D imaging', 'Surgery under local anaesthesia', 'Stitches, aftercare instructions and a follow-up visit']),
    duration: T('İşleme göre değişir; çoğunlukla tek seans', 'Depends on the procedure; often a single visit'),
    faq: [{ q: T('Cerrahi işlem sonrası iyileşme nasıl olur?', 'How is recovery after surgery?'), a: T('Birkaç gün hafif şişlik ve hassasiyet olabilir. Verilen bakım talimatlarına uyulduğunda iyileşme genellikle sorunsuz ilerler.', 'Mild swelling and tenderness for a few days is common. Following the aftercare instructions usually keeps healing smooth.') }],
  },
  {
    group: 'implant', icon: 'tooth', slug: T('yirmilik-dis-ve-dis-cekimi', 'wisdom-teeth-and-extractions'),
    name: T('Yirmilik Diş ve Diş Çekimi', 'Wisdom Teeth & Extractions'),
    promise: T('Gerekli olduğunda rahat ve kontrollü diş çekimi.', 'Comfortable, controlled extractions when they are needed.'),
    who: T('Kurtarılamayan, gömülü veya sorun çıkaran dişler için.', 'For teeth that cannot be saved, or are impacted or troublesome.'),
    steps: T(['Klinik ve röntgen değerlendirmesi', 'Lokal anestezi ile çekim', 'Gerekirse dikiş ve bakım talimatları'], ['Clinical and X-ray assessment', 'Extraction under local anaesthesia', 'Stitches if needed and aftercare instructions']),
    duration: T('Genellikle tek seans', 'Usually one visit'),
    faq: [{ q: T('Çekim sonrası nelere dikkat edilmeli?', 'What should I do after an extraction?'), a: T('İlk 24 saat çalkalamaktan, sıcak ve sert gıdalardan kaçının; verilen talimatlara uyun.', 'For 24 hours avoid rinsing, hot and hard food, and follow the instructions we give you.') }],
  },
  {
    group: 'implant', icon: 'crown', slug: T('kaplama-kopru-protez', 'crowns-bridges-dentures'),
    name: T('Kaplama, Köprü ve Protez', 'Crowns, Bridges & Dentures'),
    promise: T('Kırık veya eksik dişler için dayanıklı ve estetik restorasyonlar.', 'Durable, aesthetic restorations for broken or missing teeth.'),
    who: T('Büyük dolgusu olan, kırılan veya eksik dişleri olanlar.', 'People with large fillings, broken or missing teeth.'),
    steps: T(['Muayene ve ölçü', 'Geçici restorasyon', 'Son restorasyonun yerleştirilmesi'], ['Exam and impressions', 'Temporary restoration', 'Fitting the final restoration']),
    duration: T('2–3 seans', '2–3 visits'),
    faq: [{ q: T('Kaplama malzemesi nasıl seçilir?', 'How is the crown material chosen?'), a: T('Dişin konumu, estetik beklenti ve kapanışa göre birlikte karar veririz.', 'Together, based on tooth position, aesthetic goals and your bite.') }],
  },
  {
    group: 'emergency', icon: 'alert', slug: T('acil-dis-tedavisi', 'emergency-dental-care'),
    name: T('Acil Diş Tedavisi', 'Emergency Dental Care'),
    promise: T('Ağrı, şişlik, kırık diş: en kısa sürede randevu için bizi arayın.', 'Pain, swelling, a broken tooth: call us for the earliest appointment.'),
    who: T('Şiddetli diş ağrısı, yüzde şişlik, kırık veya çıkan diş.', 'Severe toothache, facial swelling, or a broken or knocked-out tooth.'),
    steps: T(['Bizi arayın ve durumu anlatın', 'Muayene ve ağrının giderilmesi', 'Kalıcı tedavi planı'], ['Call us and describe the problem', 'Exam and pain relief', 'A plan for lasting treatment']),
    duration: T('Duruma göre', 'Depends on the situation'),
    faq: [{ q: T('Kırılan diş parçasını ne yapmalıyım?', 'What do I do with a broken tooth fragment?'), a: T('Süt veya serum içinde saklayıp hemen bize ulaşın; kuru bırakmayın.', 'Keep it in milk or saline and contact us straight away; do not let it dry out.') }],
  },
];

export const FAQ = [
  { q: T('Muayene ücretsiz mi?', 'Is the check-up free?'), a: T('Evet, muayene ücretsizdir. Muayene sonrasında tedavi planınızı ve maliyetini yazılı olarak paylaşırız; karar tamamen size aittir.', 'Yes, the check-up is free. Afterwards we share your treatment plan and its cost in writing, and the decision is entirely yours.') },
  { q: T('Tedavi ağrılı mı olur?', 'Will treatment hurt?'), a: T('İşlemler lokal anestezi altında yapılır. Amacımız rahat bir deneyimdir; kaygılıysanız randevuda mutlaka söyleyin.', 'Procedures are done under local anaesthesia and we aim for a comfortable visit. If you feel anxious, tell us at your appointment.') },
  { q: T('İlk randevuda neler olur?', 'What happens at the first visit?'), a: T('Şikâyetlerinizi dinler, ağız muayenesi yapar, gerekirse röntgen veya 3D görüntüleme isteriz. Ardından tedavi seçenekleri ve süreyi anlatırız.', 'We listen to your concerns, examine your mouth and, if needed, take X-rays or 3D images. Then we explain your options and the timeline.') },
  { q: T('Şeffaf plak tedavisi ne kadar sürer?', 'How long do clear aligners take?'), a: T('Genellikle 6–18 ay arasındadır. Süre, dişlerin durumuna göre değişir; net süreyi planlama sonrası paylaşırız.', 'Typically 6–18 months. It depends on your teeth; we give a clear estimate after planning.') },
  { q: T('Tedavi ücretleri nasıl belirlenir?', 'How are treatment fees set?'), a: T('Muayene ücretsizdir. Sonrasında tedavi planınızı ve maliyetini yazılı olarak paylaşırız. Ödeme seçenekleri için bize ulaşabilirsiniz.', 'The check-up is free. Afterwards we share your treatment plan and its cost in writing. Contact us about payment options.') },
  { q: T('Çocuklar için de randevu alabilir miyim?', 'Do you see children?'), a: T('Evet. Çocuk diş tedavileri için ilk muayene randevusu alabilirsiniz.', 'Yes. You can book a first exam for children.') },
  { q: T('Acil durumda ne yapmalıyım?', 'What should I do in an emergency?'), a: T('Şiddetli ağrı, şişlik veya kırık diş için hemen telefonla arayın; en kısa sürede randevu vermeye çalışırız.', 'For severe pain, swelling or a broken tooth, call us right away and we will find the earliest slot.') },
];

export const POSTS = [
  { slug: T('seffaf-plak-nedir', 'what-are-clear-aligners'), date: '2026-09-15', cat: T('Şeffaf Plak', 'Clear Aligners'),
    title: T('Şeffaf plak nedir, kimler için uygundur?', 'What are clear aligners and who are they for?'),
    excerpt: T('Tel takmadan dişleri hizalayan şeffaf plakların nasıl çalıştığını ve süreci anlatıyoruz.', 'How clear aligners straighten teeth without wires, and what the process looks like.'),
    body: T(['Şeffaf plaklar, dişlerinize özel hazırlanan ve kademeli olarak dişleri hareket ettiren, ince ve çıkarılabilir apareylerdir. Tel ve braket kullanılmadığı için gündelik hayatta neredeyse fark edilmezler.', 'Süreç muayene ve dijital kayıtlarla başlar. Dişlerin hedef konumu yazılımda planlanır; her adımı görebildiğiniz bir 3D simülasyonla onay verirsiniz. Ardından plak setleri belirli aralıklarla değiştirilir.', 'Plaklardan iyi sonuç almak için günde yaklaşık 20–22 saat takmak gerekir. Çapraşıklık, aralıklı dişler ve hafif-orta kapanış sorunlarında sık tercih edilir; ancak her vakaya uygun olmayabilir. Uygunluğu muayenede birlikte değerlendiririz.'],
      ['Clear aligners are thin, removable trays made for your teeth that move them gradually. With no wires or brackets, they are barely noticeable in daily life.', 'The process starts with an exam and digital records. The target position of your teeth is planned in software, and you approve it through a 3D simulation that shows every step. The aligner sets are then changed at set intervals.', 'For good results they are worn about 20–22 hours a day. They are often chosen for crowding, gaps and mild-to-moderate bite issues, but they do not suit every case. We assess suitability together at the exam.']) },
  { slug: T('cerrahi-guide-ile-implant', 'guided-implant-surgery-explained'), date: '2026-09-10', cat: T('İmplant', 'Implants'),
    title: T('Cerrahi guide ile implant nasıl yapılır?', 'How does guided implant surgery work?'),
    excerpt: T('Dijital plan ve kişiye özel kılavuzla implantın planlandığı yere yerleştirilmesi.', 'A digital plan and a custom guide place the implant exactly where it was planned.'),
    body: T(['Cerrahi guide, implantın yerini ve açısını ameliyat sırasında yönlendiren, kişiye özel hazırlanmış bir kılavuzdur.', 'Önce 3D görüntüleme ve dijital ölçüler birleştirilir. Yazılım ortamında kemik yapısı, komşu dişler ve sinir gibi önemli bölgeler göz önüne alınarak implantın konumu planlanır. Sonra bu plana göre guide hazırlanır.', 'Cerrahi sırasında guide ağıza yerleştirilir ve implant bu kılavuz eşliğinde konumlandırılır. Bu yöntem işlemi daha öngörülebilir hale getirir. Yine de her vakada guide gerekmez; en doğru yöntemi muayene sonrası birlikte seçeriz.'],
      ['A surgical guide is a custom-made template that steers the position and angle of the implant during surgery.', 'First, 3D imaging and digital impressions are combined. In software, the implant position is planned with the bone, neighbouring teeth and nerve in mind. The guide is then produced from that plan.', 'During surgery the guide sits in the mouth and the implant is positioned through it. This makes the procedure more predictable. Not every case needs a guide, though; we choose the best method together after your exam.']) },
  { slug: T('dis-tasi-temizligi-ne-siklikla', 'how-often-scaling'), date: '2026-09-05', cat: T('Koruyucu Bakım', 'Preventive Care'),
    title: T('Diş taşı temizliği ne sıklıkla yapılmalı?', 'How often should you have your teeth scaled?'),
    excerpt: T('Düzenli temizlik neden diş eti hastalıklarını önlemede en kolay adımdır?', 'Why regular cleaning is the easiest step against gum disease.'),
    body: T(['Diş taşı, fırçalamayla çıkmayan sertleşmiş plaktır. Diş etinde iltihaba ve zamanla kemik kaybına yol açabilir.', 'Çoğu kişi için yılda iki kez kontrol ve temizlik yeterlidir. Diş eti problemi olanlar veya sigara kullananlar için daha sık aralıklar gerekebilir.', 'Günde iki kez fırçalamak ve diş ipi veya arayüz fırçası kullanmak temizlik aralığını uzatır. Diş eti kanaması fark ederseniz beklemeden muayeneye gelin.'],
      ['Tartar is hardened plaque that brushing cannot remove. It can inflame the gums and, over time, lead to bone loss.', 'For most people a check-up and cleaning twice a year is enough. People with gum problems or who smoke may need shorter intervals.', 'Brushing twice a day and using floss or interdental brushes helps. If you notice bleeding gums, come in without waiting.']) },
  { slug: T('cocuklarda-ilk-dis-hekimi-ziyareti', 'first-dental-visit-for-children'), date: '2026-08-28', cat: T('Çocuk', 'Children'),
    title: T('Çocuklarda ilk diş hekimi ziyareti', "Your child's first dental visit"),
    excerpt: T('İlk ziyaret ne zaman olmalı ve çocuğunuzu nasıl hazırlamalısınız?', 'When should it happen and how can you prepare your child?'),
    body: T(['İlk süt dişi çıktığında, en geç bir yaşına kadar ilk kontrol önerilir. Amaç tedavi değil, tanışma ve koruyucu yönlendirmedir.', 'Ziyaretten önce çocuğa diş hekimini korkutucu bir yer gibi anlatmamak önemlidir. "Dişlerine bakacağız" gibi sade ve olumlu bir dil kullanın.', 'Erken dönemde fissür örtücü ve flor gibi koruyucu uygulamalar çürük riskini azaltır. Düzenli kontroller çocuğun diş hekimine güvenle alışmasını sağlar.'],
      ['A first check-up is recommended when the first baby tooth appears, and by the first birthday at the latest. The goal is to meet the dentist and get preventive advice, not treatment.', 'Avoid describing the dentist as a scary place. Simple, positive words like "we will look at your teeth" work well.', 'Early preventive care such as sealants and fluoride lowers cavity risk. Regular visits help your child feel at ease.']) },
  { slug: T('dis-beyazlatma-bilmeniz-gerekenler', 'teeth-whitening-what-to-know'), date: '2026-08-20', cat: T('Estetik', 'Cosmetic'),
    title: T('Diş beyazlatma: bilmeniz gerekenler', 'Teeth whitening: what you need to know'),
    excerpt: T('Beyazlatma öncesi muayenenin önemi ve sonuçların kalıcılığı.', 'Why an exam comes first and how long results last.'),
    body: T(['Beyazlatma, dişlerin yüzeyindeki lekeleri ve renk tonunu açan bir işlemdir. Dolgu ve kaplamaların rengini değiştirmez; bu yüzden önce muayene gerekir.', 'İşlem öncesinde diş taşı temizlenir ve çürük veya diş eti sorunları varsa tedavi edilir. Sonrasında diş eti korunarak jel uygulanır.', 'Kahve, çay, sigara gibi alışkanlıklar rengin geri dönmesini hızlandırır. Bakım önerilerine uyarak sonucu daha uzun süre koruyabilirsiniz.'],
      ['Whitening lightens stains and the overall shade of your teeth. It does not change the colour of fillings or crowns, which is why an exam comes first.', 'Before the procedure, tartar is removed and any decay or gum problems are treated. The gel is then applied with the gums protected.', 'Coffee, tea and smoking make the colour return faster. Following our aftercare advice helps the result last longer.']) },
  { slug: T('acil-dis-agrisinda-ne-yapmali', 'what-to-do-in-a-dental-emergency'), date: '2026-08-12', cat: T('Acil', 'Emergency'),
    title: T('Acil diş ağrısında ne yapmalı?', 'What to do in a dental emergency'),
    excerpt: T('Ağrı, şişlik veya kırık dişte ilk yapılacaklar.', 'First steps for pain, swelling or a broken tooth.'),
    body: T(['Şiddetli diş ağrısında ağzınızı ılık suyla çalkalayın ve diş ipi ile dişlerin arasını temizleyin. Ağrı kesici için ambalajdaki dozu aşmayın; aspirini doğrudan dişe veya diş etine koymayın.', 'Yüzde şişlik, ateş veya yutkunma güçlüğü varsa vakit kaybetmeden sağlık kuruluşuna başvurun. Kırık diş parçasını süt veya serum içinde saklayın.', 'Bu bilgiler genel bilgilendirme amaçlıdır ve muayenenin yerini tutmaz. Acil durumda bizi arayın.'],
      ['For severe toothache, rinse with warm water and floss gently. Do not exceed the dose on the painkiller pack, and never place aspirin directly on the tooth or gum.', 'If you have facial swelling, fever or trouble swallowing, seek medical care without delay. Keep a broken tooth fragment in milk or saline.', 'This is general information and does not replace an exam. In an emergency, call us.']) },
];
